language: ruby

# This will enable the docker base infrastructure for
# travis tests. It should result in faster test vm load times.
sudo: false
rvm:
  - "2.1.6"
  - ruby-head

install:
  - echo "using standalone bundle"

script:
  # Run all specs.
  - "bundle/bin/rspec"

matrix:
  allow_failures:
    - rvm: ruby-head