language: ruby
cache: bundler
# This will enable the docker base infrastructure for
# travis tests. It should result in faster test vm load times.
sudo: false
rvm:
  - "2.7"
  - ruby-head


install: bundle install --path vendor/bundle/

script:
  # Run all specs.
  - "bundle exec rspec"

matrix:
  allow_failures:
    - rvm: ruby-head